import { ProductInput } from "../validators/product";

export const productsToSeed: ProductInput[] = [
  {
    name: "Luxury Mystery Beauty Box",
    slug: "luxury-mystery-beauty-box",
    category: "Mystery Gifts",
    description:
      "Indulge in the excitement of surprise with our Luxury Mystery Beauty Box! Carefully curated by beauty experts, each box contains a selection of high-end skincare, makeup, and fragrance items from top luxury brands. Whether you're treating yourself or gifting a loved one, this box ensures a thrilling unboxing experience with every order. Inside, you'll find premium serums, face masks, lipsticks, or even exclusive, limited-edition beauty products. The mystery element adds to the fun, making each box unique and exciting. Ideal for beauty lovers who enjoy discovering new products without the hassle of shopping. Every product is chosen to pamper, enhance, and elevate your skincare or makeup routine. With a mix of full-size and deluxe samples, this box provides unbeatable value. Elevate your self-care routine and indulge in a touch of luxury today!",
    isPublished: true,
    countInStock: 15,
    tags: ["beauty", "mystery", "gift", "luxury", "self-care"],
    avgRating: 4.7,
    numReviews: 120,
    numSales: 300,
    price: 4999,
  },
  {
    name: "Self-Care Spa Set",
    slug: "self-care-spa-set",
    category: "Beauty & Wellness",
    description:
      "Transform your home into a spa with our luxurious Self-Care Spa Set. This all-in-one relaxation package includes rejuvenating bath salts, deeply hydrating body butter, calming essential oils, and a soft, plush eye mask for the ultimate self-care experience. Designed to relieve stress and promote relaxation, each ingredient has been carefully selected to nourish your skin and soothe your senses. The bath salts dissolve effortlessly, infusing your bathwater with essential minerals for a therapeutic soak. The body butter is rich in shea butter and vitamin E, leaving your skin soft, smooth, and moisturized for hours. The essential oils blend contains calming lavender and eucalyptus to ease tension and enhance sleep quality. Whether you're winding down after a long day or treating yourself to a weekend pamper session, this spa set is the perfect companion for relaxation. Makes a thoughtful gift for anyone in need of a little TLC.",
    isPublished: true,
    countInStock: 20,
    tags: ["spa", "wellness", "relaxation", "gift", "self-care"],
    avgRating: 4.9,
    numReviews: 85,
    numSales: 250,
    price: 3999,
  },
  {
    name: "Mystery Perfume Box",
    slug: "mystery-perfume-box",
    category: "Mystery Gifts",
    description:
      "Unveil the perfect fragrance with our Mystery Perfume Box, featuring a surprise selection of three premium fragrance samples. Each box is carefully curated with scents from top designers and niche perfume houses, ensuring a diverse and delightful olfactory experience. Whether you love floral, woody, musky, or citrusy notes, this mystery box introduces you to new signature scents. Perfect for fragrance enthusiasts who enjoy experimenting with different perfumes before committing to a full-sized bottle. The element of surprise makes every unboxing thrilling, while the high-quality selections ensure satisfaction. Our perfumes are long-lasting and crafted with the finest ingredients to provide an elegant, sophisticated aroma. Whether you're looking for a fresh daytime scent, a romantic evening fragrance, or a bold statement perfume, this box has something special for every occasion. Treat yourself or surprise a loved one with this unique, sensory-filled gift!",
    isPublished: true,
    countInStock: 25,
    tags: ["fragrance", "perfume", "mystery", "luxury", "gifts"],
    avgRating: 4.8,
    numReviews: 95,
    numSales: 180,
    price: 2999,
  },
  {
    name: "Aromatherapy Candle Gift Set",
    slug: "aromatherapy-candle-set",
    category: "Home Decor",
    description:
      "Fill your home with calming scents with our Aromatherapy Candle Gift Set, designed to create a relaxing and inviting atmosphere. Each set includes four premium soy wax candles infused with natural essential oils, offering a variety of soothing aromas like lavender, vanilla, eucalyptus, and sandalwood. These candles burn cleanly and evenly, filling your space with a gentle, lingering fragrance. Ideal for stress relief, meditation, or simply creating a cozy ambiance, they make the perfect addition to any home. The elegant glass jars add a touch of sophistication to any decor, while the long burn time ensures hours of aromatic bliss. Whether you're unwinding after a long day or setting the mood for a romantic evening, these candles provide the perfect touch. Beautifully packaged, they also make a thoughtful and luxurious gift for friends, family, or anyone in need of a little relaxation.",
    isPublished: true,
    countInStock: 35,
    tags: ["candles", "aromatherapy", "home", "gift", "relaxation"],
    avgRating: 4.9,
    numReviews: 160,
    numSales: 350,
    price: 3499,
  },
  {
    name: "Mystery Skincare Deluxe Box",
    slug: "mystery-skincare-deluxe-box",
    category: "Mystery Gifts",
    description:
      "Give your skin the luxury it deserves with our Mystery Skincare Deluxe Box. Each box contains a surprise selection of high-end skincare products, including moisturizers, serums, face masks, and cleansers from premium brands. Designed to nourish and rejuvenate, this box caters to all skin types, helping to enhance hydration, radiance, and overall skin health. Whether you're an avid skincare lover or someone looking to explore new products, this mystery box ensures excitement and value with every purchase. Packed with dermatologist-approved formulas and natural ingredients, the products included are carefully selected to deliver noticeable results. It's the perfect gift for anyone looking to elevate their skincare routine while enjoying the thrill of mystery. Treat yourself or surprise a loved one with this exclusive, limited-edition box filled with self-care essentials!",
    isPublished: true,
    countInStock: 25,
    tags: ["skincare", "mystery", "beauty", "luxury", "self-care"],
    avgRating: 4.8,
    numReviews: 95,
    numSales: 220,
    price: 5499,
  },
  {
    name: "Lavender Sleep & Relaxation Kit",
    slug: "lavender-sleep-relaxation-kit",
    category: "Beauty & Wellness",
    description:
      "Drift into a peaceful slumber with our Lavender Sleep & Relaxation Kit, specially designed to help you unwind and de-stress. This soothing set includes a lavender-infused pillow mist, a calming essential oil roller, and a plush satin sleep mask to enhance your nighttime routine. The delicate floral aroma of lavender is known for its ability to ease anxiety, reduce stress, and improve sleep quality. Simply spritz your pillow with the mist, apply the essential oil to your pulse points, and slip on the luxurious sleep mask for a restful, uninterrupted sleep. Perfect for those who struggle with insomnia or simply want to enhance their bedtime ritual, this set makes a wonderful self-care treat or gift for loved ones. Experience deep relaxation and wake up feeling refreshed and rejuvenated every morning.",
    isPublished: true,
    countInStock: 35,
    tags: ["sleep", "relaxation", "lavender", "wellness", "self-care"],
    avgRating: 4.8,
    numReviews: 120,
    numSales: 260,
    price: 2999,
  },
  {
    name: "Mystery Jewelry Gift Box",
    slug: "mystery-jewelry-gift-box",
    category: "Mystery Gifts",
    description:
      "Love surprises? Our Mystery Jewelry Gift Box is the perfect way to discover elegant, stylish accessories with a touch of mystery. Each box contains a carefully curated selection of stunning jewelry pieces, including necklaces, bracelets, rings, or earrings from trendy and classic designs. Made with high-quality materials such as sterling silver, gold plating, and premium gemstones, every piece is chosen to complement various styles and occasions. Whether you're gifting it to someone special or indulging in a little self-love, this mystery box guarantees a delightful unboxing experience. Ideal for those who enjoy accessorizing and discovering unique pieces, this limited-edition set offers unbeatable value. Unwrap elegance and add a touch of sparkle to your jewelry collection today!",
    isPublished: true,
    countInStock: 20,
    tags: ["jewelry", "mystery", "gift", "fashion", "accessories"],
    avgRating: 4.7,
    numReviews: 105,
    numSales: 240,
    price: 4499,
  },
  {
    name: "Luxury Scented Candle Trio",
    slug: "luxury-scented-candle-trio",
    category: "Home Decor",
    description:
      "Set the mood and elevate your home’s ambiance with our Luxury Scented Candle Trio. This exquisite set features three hand-poured soy wax candles infused with premium essential oils, providing a long-lasting, clean burn. Each candle is thoughtfully crafted to deliver a distinct fragrance experience—choose from calming lavender, uplifting citrus, and warm vanilla. Whether you’re setting a relaxing atmosphere for a cozy evening, creating a spa-like experience at home, or adding a decorative touch to your space, these candles provide the perfect finishing touch. Their elegant glass jars complement any decor, making them an ideal gift for housewarmings, holidays, or self-care indulgence. Enjoy hours of aromatic bliss with our premium candle trio, designed to soothe the senses and brighten any room.",
    isPublished: true,
    countInStock: 35,
    tags: ["candles", "aromatherapy", "luxury", "home", "relaxation"],
    avgRating: 4.9,
    numReviews: 170,
    numSales: 330,
    price: 3999,
  },
  {
    name: "Luxury Beauty Mystery Box",
    slug: "luxury-beauty-mystery-box",
    category: "Mystery Gifts",
    description:
      "Unwrap the thrill of luxury with our exclusive Beauty Mystery Box! Each box contains a surprise selection of high-end skincare, makeup, and self-care products from top beauty brands. Expect full-sized and deluxe items ranging from serums and moisturizers to lipsticks and eyeshadow palettes. Perfect for beauty lovers who enjoy discovering new products, this box is packed with premium, hand-picked essentials to elevate your skincare and makeup routine. A treat for yourself or a fantastic gift, this mystery box offers unbeatable value and an element of surprise!",
    isPublished: true,
    countInStock: 50,
    tags: ["beauty", "mystery", "luxury", "skincare", "makeup"],
    avgRating: 4.9,
    numReviews: 310,
    numSales: 750,
    price: 7999,
  },
  {
    name: "Spa & Relaxation Mystery Box",
    slug: "spa-relaxation-mystery-box",
    category: "Beauty & Wellness",
    description:
      "Turn your home into a spa with our luxurious Spa & Relaxation Mystery Box! Each box includes a carefully curated selection of bath salts, body scrubs, essential oils, candles, and self-care items designed to promote relaxation and well-being. Infused with soothing ingredients like lavender, eucalyptus, and chamomile, these products help melt away stress and leave your skin feeling refreshed. Whether it's a self-care Sunday or a thoughtful gift, this box delivers the ultimate spa experience without leaving your home.",
    isPublished: true,
    countInStock: 40,
    tags: ["spa", "relaxation", "self-care", "gift", "wellness"],
    avgRating: 4.8,
    numReviews: 275,
    numSales: 620,
    price: 5999,
  },
  {
    name: "Mystery Perfume Gift Box",
    slug: "mystery-perfume-gift-box",
    category: "Mystery Gifts",
    description:
      "Discover your new signature scent with our Mystery Perfume Gift Box! Featuring a selection of luxurious, high-end fragrances from top perfume houses, this box includes a mix of miniatures, travel-sized bottles, and full-size surprises. Whether you love floral, citrus, woody, or oriental scents, each box is designed to introduce you to stunning new fragrances. Perfect for perfume lovers or those who love a little mystery, this box brings elegance and sophistication with every unboxing experience.",
    isPublished: true,
    countInStock: 35,
    tags: ["perfume", "fragrance", "mystery", "luxury", "scent"],
    avgRating: 4.7,
    numReviews: 220,
    numSales: 500,
    price: 6999,
  },
  {
    name: "Jewelry Mystery Gift Box",
    slug: "jewelry-mystery-gift-box",
    category: "Jewelry",
    description:
      "Love surprises? Our Jewelry Mystery Gift Box contains a stunning selection of handpicked, high-quality jewelry pieces! Each box includes a mix of earrings, necklaces, bracelets, and rings crafted from premium materials like sterling silver, gold plating, and semi-precious gemstones. Whether you’re looking for elegant everyday pieces or dazzling statement jewelry, this mystery box guarantees an exciting unboxing experience. Perfect as a treat for yourself or a unique gift for a loved one.",
    isPublished: true,
    countInStock: 30,
    tags: ["jewelry", "mystery", "gift", "fashion", "accessories"],
    avgRating: 4.8,
    numReviews: 265,
    numSales: 580,
    price: 4499,
  },
  {
    name: "Deluxe Skincare Gift Box",
    slug: "deluxe-skincare-gift-box",
    category: "Beauty & Wellness",
    description:
      "Pamper your skin with our Deluxe Skincare Gift Box, filled with premium skincare essentials! This box includes luxurious face masks, serums, moisturizers, and cleansers from top-rated skincare brands. Designed to hydrate, brighten, and rejuvenate, these products work together to give you that radiant glow. Whether you're treating yourself or gifting someone special, this box is the ultimate skincare indulgence!",
    isPublished: true,
    countInStock: 45,
    tags: ["skincare", "luxury", "self-care", "glow", "beauty"],
    avgRating: 4.9,
    numReviews: 290,
    numSales: 670,
    price: 7999,
  },
  {
    name: "Luxury Haircare Mystery Box",
    slug: "luxury-haircare-mystery-box",
    category: "Beauty & Wellness",
    description:
      "Give your hair the VIP treatment with our Luxury Haircare Mystery Box! Packed with premium shampoos, conditioners, serums, and styling products from top haircare brands, this box is designed to nourish, strengthen, and enhance your locks. Whether you have curly, straight, or textured hair, each box includes a variety of high-end products tailored to improve hair health and styling. A perfect surprise for anyone who loves taking care of their hair!",
    isPublished: true,
    countInStock: 38,
    tags: ["haircare", "mystery", "luxury", "hair", "beauty"],
    avgRating: 4.7,
    numReviews: 215,
    numSales: 490,
    price: 6499,
  },
  {
    name: "Self-Care Mystery Box",
    slug: "self-care-mystery-box",
    category: "Beauty & Wellness",
    description:
      "Prioritize self-care with our Self-Care Mystery Box! This box includes a variety of wellness and relaxation products such as aromatherapy oils, luxurious bath bombs, calming teas, and mindfulness journals. Designed to promote inner peace and well-being, this box is perfect for unwinding after a long day. Treat yourself or send it as a thoughtful gift to someone who deserves some relaxation and self-love!",
    isPublished: true,
    countInStock: 50,
    tags: ["self-care", "wellness", "gift", "relaxation", "spa"],
    avgRating: 4.8,
    numReviews: 240,
    numSales: 530,
    price: 5999,
  },
  {
    name: "Ultimate Nail Care Gift Box",
    slug: "ultimate-nail-care-gift-box",
    category: "Beauty & Wellness",
    description:
      "Get salon-quality nails at home with our Ultimate Nail Care Gift Box! Featuring a mix of premium nail polishes, strengthening treatments, cuticle oils, and high-quality manicure tools, this set has everything needed for flawless nails. Whether you love bold colors or natural shades, this mystery box offers a curated selection of trendy nail essentials. Perfect for nail enthusiasts or anyone who enjoys pampering their hands.",
    isPublished: true,
    countInStock: 42,
    tags: ["nails", "beauty", "mystery", "self-care", "manicure"],
    avgRating: 4.9,
    numReviews: 275,
    numSales: 610,
    price: 4999,
  },
  {
    name: "Handmade Soap & Bath Essentials Box",
    slug: "handmade-soap-bath-essentials-box",
    category: "Beauty & Wellness",
    description:
      "Indulge in natural luxury with our Handmade Soap & Bath Essentials Box! This set includes a variety of handcrafted, organic soaps infused with essential oils, along with bath salts and scrubs for the ultimate relaxation experience. Each soap is made with nourishing ingredients like coconut oil, shea butter, and natural botanicals, making it perfect for sensitive skin. A wonderful gift for those who appreciate artisanal skincare and spa-like experiences at home.",
    isPublished: true,
    countInStock: 50,
    tags: ["soap", "bath", "natural", "skincare", "gift"],
    avgRating: 4.9,
    numReviews: 300,
    numSales: 680,
    price: 3999,
  },
  {
    name: "Glow-Up Beauty Mystery Box",
    slug: "glow-up-beauty-mystery-box",
    category: "Mystery Gifts",
    description:
      "Unbox the magic of a complete beauty transformation with our Glow-Up Beauty Mystery Box! This box includes a curated selection of high-end beauty essentials, from premium skincare to stunning makeup items. Inside, you may find hydrating serums, long-lasting lipsticks, dazzling highlighters, and more. Each box is designed to bring a touch of luxury to your routine, helping you achieve a radiant, camera-ready glow. Perfect for beauty lovers who love a little mystery in their collection!",
    isPublished: true,
    countInStock: 40,
    tags: ["beauty", "glow", "mystery", "skincare", "makeup"],
    avgRating: 4.9,
    numReviews: 300,
    numSales: 720,
    price: 7499,
  },
  {
    name: "Midnight Spa Retreat Box",
    slug: "midnight-spa-retreat-box",
    category: "Beauty & Wellness",
    description:
      "Create your own personal spa experience at home with the Midnight Spa Retreat Box! This premium selection includes everything needed for a night of relaxation, from lavender-infused bath salts to rich body butters, exfoliating scrubs, and a calming candle. The soothing scents and skin-loving formulas make this the perfect self-care gift for anyone who deserves to unwind and pamper themselves. A true luxury spa moment in a box!",
    isPublished: true,
    countInStock: 35,
    tags: ["spa", "relaxation", "self-care", "wellness", "beauty"],
    avgRating: 4.8,
    numReviews: 270,
    numSales: 620,
    price: 6599,
  },
  {
    name: "Secret Scent Perfume Box",
    slug: "secret-scent-perfume-box",
    category: "Mystery Gifts",
    description:
      "Let your senses take a journey with the Secret Scent Perfume Box! This mystery fragrance box includes a mix of sample and full-size perfumes from premium brands, featuring a variety of floral, woody, and fresh scents. Each box is curated to introduce you to your next signature scent while providing an exciting and luxurious unboxing experience. Perfect for perfume lovers and those who love surprises!",
    isPublished: true,
    countInStock: 30,
    tags: ["perfume", "fragrance", "luxury", "mystery", "gift"],
    avgRating: 4.7,
    numReviews: 250,
    numSales: 540,
    price: 6899,
  },
  {
    name: "Jewelry & Beauty Surprise Box",
    slug: "jewelry-beauty-surprise-box",
    category: "Jewelry",
    description:
      "A perfect blend of sparkle and self-care, the Jewelry & Beauty Surprise Box contains a mix of stunning accessories and premium beauty products. Expect a beautiful selection of rings, necklaces, or bracelets paired with skincare and makeup goodies. Whether you’re treating yourself or someone special, this box delivers an elegant unboxing experience filled with luxury and charm!",
    isPublished: true,
    countInStock: 25,
    tags: ["jewelry", "beauty", "mystery", "luxury", "gift"],
    avgRating: 4.9,
    numReviews: 280,
    numSales: 600,
    price: 4999,
  },
  {
    name: "Luxe Haircare Essentials Box",
    slug: "luxe-haircare-essentials-box",
    category: "Beauty & Wellness",
    description:
      "Give your hair the ultimate care with the Luxe Haircare Essentials Box! This set includes salon-quality shampoos, conditioners, nourishing hair masks, and heat protection sprays to keep your locks strong, shiny, and healthy. Perfect for all hair types, this box is designed to enhance your hair routine with premium products that bring professional results.",
    isPublished: true,
    countInStock: 50,
    tags: ["haircare", "beauty", "luxury", "self-care", "gift"],
    avgRating: 4.8,
    numReviews: 260,
    numSales: 570,
    price: 5799,
  },
  {
    name: "Luxury Candle & Skincare Box",
    slug: "luxury-candle-skincare-box",
    category: "Home Decor",
    description:
      "Set the mood for ultimate relaxation with the Luxury Candle & Skincare Box! This box includes a hand-poured soy candle in a soothing scent, along with a collection of skincare essentials like face masks, lip balms, and hydrating creams. A perfect gift for those who love self-care, ambiance, and a little bit of indulgence!",
    isPublished: true,
    countInStock: 40,
    tags: ["candle", "skincare", "relaxation", "self-care", "luxury"],
    avgRating: 4.9,
    numReviews: 290,
    numSales: 680,
    price: 5999,
  },
  {
    name: "The Ultimate Bath Ritual Box",
    slug: "ultimate-bath-ritual-box",
    category: "Beauty & Wellness",
    description:
      "Transform your bathtub into a spa oasis with the Ultimate Bath Ritual Box! Featuring handcrafted bath bombs, aromatic bath salts, luxurious bubble baths, and a silk-soft bath sponge, this box is designed for pure indulgence. Infused with natural ingredients and essential oils, each product is carefully selected to help you unwind, de-stress, and enjoy a moment of bliss.",
    isPublished: true,
    countInStock: 45,
    tags: ["bath", "spa", "relaxation", "self-care", "luxury"],
    avgRating: 4.8,
    numReviews: 310,
    numSales: 720,
    price: 6999,
  },
  {
    name: "Secret Glow-Up Box",
    slug: "secret-glow-up-box",
    category: "Mystery Gifts",
    description:
      "Looking for a beauty boost? The Secret Glow-Up Box is packed with surprise skincare and makeup items designed to enhance your natural glow. Expect luxury face serums, radiant highlighters, nourishing lip treatments, and more. With a mix of bestselling and hidden gem products, this mystery box is the perfect way to treat yourself!",
    isPublished: true,
    countInStock: 35,
    tags: ["beauty", "glow", "mystery", "luxury", "makeup"],
    avgRating: 4.9,
    numReviews: 320,
    numSales: 750,
    price: 7499,
  },
  {
    name: "Glam Night Beauty Box",
    slug: "glam-night-beauty-box",
    category: "Mystery Gifts",
    description:
      "Get ready for a glamorous night out with the Glam Night Beauty Box! This box includes bold lipsticks, long-lasting setting sprays, shimmering eyeshadows, and luxurious skincare to prep your skin for a flawless finish. Whether you're planning a special event or just love a little extra glam, this mystery box has everything needed to create a stunning look!",
    isPublished: true,
    countInStock: 30,
    tags: ["beauty", "makeup", "mystery", "glam", "luxury"],
    avgRating: 4.8,
    numReviews: 280,
    numSales: 690,
    price: 7299,
  },
  {
    name: "Pamper Me Luxury Gift Box",
    slug: "pamper-me-luxury-gift-box",
    category: "Beauty & Wellness",
    description:
      "Treat yourself or someone special to the Pamper Me Luxury Gift Box! This indulgent box includes rich body lotions, silky face masks, premium lip care, and a calming pillow spray for the ultimate relaxation experience. Designed to provide a full-body self-care ritual, this box is perfect for anyone who deserves a little extra love and attention.",
    isPublished: true,
    countInStock: 50,
    tags: ["self-care", "beauty", "luxury", "gift", "wellness"],
    avgRating: 4.9,
    numReviews: 330,
    numSales: 770,
    price: 7999,
  },
  {
    name: "Golden Glow Mystery Beauty Box",
    slug: "golden-glow-mystery-beauty-box",
    category: "Mystery Gifts",
    description:
      "Step into luxury with the Golden Glow Mystery Beauty Box! This exclusive box is filled with high-end skincare and makeup designed to give your skin a radiant glow. From illuminating serums to dazzling highlighters, each item is carefully chosen to enhance your natural beauty. Perfect for those who love surprises and premium beauty products!",
    isPublished: true,
    countInStock: 30,
    tags: ["beauty", "glow", "mystery", "luxury", "makeup"],
    avgRating: 4.9,
    numReviews: 260,
    numSales: 710,
    price: 8299,
  },
  {
    name: "Enchanted Spa Retreat Box",
    slug: "enchanted-spa-retreat-box",
    category: "Beauty & Wellness",
    description:
      "Transform your self-care routine with the Enchanted Spa Retreat Box! This box features luxurious bath bombs, essential oil-infused body scrubs, and an ultra-hydrating face mask. Indulge in a relaxing spa experience from the comfort of your home, complete with calming aromas and nourishing ingredients. A must-have for anyone looking to unwind in style!",
    isPublished: true,
    countInStock: 40,
    tags: ["spa", "self-care", "relaxation", "wellness", "beauty"],
    avgRating: 4.8,
    numReviews: 240,
    numSales: 650,
    price: 6599,
  },
  {
    name: "Velvet Kiss Lipstick Collection Box",
    slug: "velvet-kiss-lipstick-collection-box",
    category: "Mystery Gifts",
    description:
      "Pucker up for the ultimate lipstick surprise! The Velvet Kiss Lipstick Collection Box includes a mix of matte, glossy, and long-wear lip colors from top beauty brands. Expect rich pigments, nourishing formulas, and shades perfect for every occasion. Whether you love bold reds or soft nudes, this mystery box has a lip color for everyone!",
    isPublished: true,
    countInStock: 25,
    tags: ["lipstick", "beauty", "mystery", "makeup", "luxury"],
    avgRating: 4.7,
    numReviews: 220,
    numSales: 590,
    price: 5499,
  },
  {
    name: "Crystal Glow Skincare Box",
    slug: "crystal-glow-skincare-box",
    category: "Beauty & Wellness",
    description:
      "Experience the magic of crystal-infused skincare with the Crystal Glow Skincare Box! Featuring gemstone-inspired face masks, hydrating facial oils, and a rose quartz roller, this box is designed to enhance your natural glow while promoting self-care and relaxation. A must-have for skincare lovers who believe in the power of beauty and energy!",
    isPublished: true,
    countInStock: 35,
    tags: ["skincare", "self-care", "glow", "beauty", "crystal"],
    avgRating: 4.9,
    numReviews: 270,
    numSales: 630,
    price: 6899,
  },
  {
    name: "Midnight Elegance Perfume Box",
    slug: "midnight-elegance-perfume-box",
    category: "Mystery Gifts",
    description:
      "Discover enchanting new scents with the Midnight Elegance Perfume Box! This luxurious collection includes mini and full-sized perfumes from well-known fragrance houses. Featuring a mix of floral, woody, and musky aromas, each box is designed to introduce you to a world of elegance and sophistication.",
    isPublished: true,
    countInStock: 30,
    tags: ["perfume", "fragrance", "mystery", "luxury", "gift"],
    avgRating: 4.8,
    numReviews: 250,
    numSales: 580,
    price: 7299,
  },
  {
    name: "Romantic Rose Spa Box",
    slug: "romantic-rose-spa-box",
    category: "Beauty & Wellness",
    description:
      "Indulge in the timeless scent of roses with the Romantic Rose Spa Box! Featuring a luxurious rose-scented candle, bath salts, body lotion, and a silk robe, this box is designed for those who love elegance and relaxation. A perfect gift for anniversaries, birthdays, or a well-deserved self-care day!",
    isPublished: true,
    countInStock: 50,
    tags: ["spa", "romance", "beauty", "relaxation", "self-care"],
    avgRating: 4.9,
    numReviews: 290,
    numSales: 720,
    price: 7999,
  },
  {
    name: "Ultimate Nail Art Surprise Box",
    slug: "ultimate-nail-art-surprise-box",
    category: "Beauty & Wellness",
    description:
      "Get ready for a nail makeover with the Ultimate Nail Art Surprise Box! This box includes high-quality nail polishes, press-on nails, nail decals, and professional tools for a flawless manicure at home. Whether you love bold colors or elegant designs, this box is perfect for nail enthusiasts!",
    isPublished: true,
    countInStock: 45,
    tags: ["nails", "beauty", "self-care", "manicure", "gift"],
    avgRating: 4.8,
    numReviews: 310,
    numSales: 710,
    price: 6799,
  },
  {
    name: "Luxury Sleep & Relaxation Box",
    slug: "luxury-sleep-relaxation-box",
    category: "Beauty & Wellness",
    description:
      "Improve your beauty sleep with the Luxury Sleep & Relaxation Box! This set includes silk pillowcases, lavender pillow mists, calming herbal teas, and an ultra-soft sleep mask. Designed to help you unwind and achieve the best sleep possible, this box is a dream come true for relaxation lovers!",
    isPublished: true,
    countInStock: 40,
    tags: ["sleep", "wellness", "relaxation", "beauty", "gift"],
    avgRating: 4.9,
    numReviews: 270,
    numSales: 690,
    price: 7499,
  },
  {
    name: "Deluxe Spa & Beauty Box",
    slug: "deluxe-spa-beauty-box",
    category: "Beauty & Wellness",
    description:
      "Experience a five-star spa day at home with the Deluxe Spa & Beauty Box! This all-in-one relaxation package includes high-end skincare, body oils, bath salts, and a luxury scented candle. Perfect for those who deserve some pampering and self-care!",
    isPublished: true,
    countInStock: 50,
    tags: ["spa", "luxury", "beauty", "self-care", "relaxation"],
    avgRating: 4.9,
    numReviews: 320,
    numSales: 740,
    price: 8999,
  },
  {
    name: "Winter Wonderland Beauty Box",
    slug: "winter-wonderland-beauty-box",
    category: "Mystery Gifts",
    description:
      "Celebrate the magic of winter with the Winter Wonderland Beauty Box! This seasonal mystery box includes hydrating skincare, shimmering makeup, and cozy self-care essentials. Expect to find winter-inspired lip balms, glowing highlighters, and hand creams to keep your skin radiant all season long!",
    isPublished: true,
    countInStock: 40,
    tags: ["winter", "beauty", "mystery", "self-care", "skincare"],
    avgRating: 4.8,
    numReviews: 300,
    numSales: 700,
    price: 7999,
  },
];
